name: backfill
on:
  workflow_dispatch:
    inputs:
      days:
        type: string
        required: true
        default: "7"
        description: "How many days of orders to backfill"
jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Invoke Backfill Lambda function
      uses: gagoar/invoke-aws-lambda@v3.3.1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.RETROBOT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RETROBOT_AWS_SECRET_ACCESS_KEY }}
        REGION: us-east-2
        FunctionName: ${{ secrets.RETROBOT_FUNCTION_NAME }}
        Payload: '{ "days": ${{ github.event.inputs.days }} }'
